services:
  devcontainer:
    image: mcr.microsoft.com/vscode/devcontainers/dotnet:10.0
    env_file:
      - ./.env
    volumes:
      - ../workspace:/workspace:cached
      - ./scripts/:/scripts:ro,cached
    # Overrides default command so things don't shut down after the process ends.
    #entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 
    
networks:
  default:
    name: devcontainer-dotnet